name: deep_dive_get_cli
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  faker: ^2.1.0
  flutter:
    sdk: flutter
  flutter_image_stack: ^0.0.7
  get: 4.6.6
  get_storage: ^2.1.1
  google_fonts: ^6.1.0
  http: ^1.2.0
  story_view: ^0.16.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - 'assets/images/profile/'
    - 'assets/images/post/'
    - 'assets/images/story/'
    - 'assets/icons/'
